#!/bin/bash

# Enable the proxy extension in notebook and lab
jupyter serverextension enable --py jupyter_server_proxy
jupyter labextension install @jupyterlab/server-proxy
jupyter lab build

code-server --install-extension ms-python.python

pip install jupyterlab-git
# Install the VS code proxy
pip install -e.

# git clone https://github.com/Center-for-Health-Data-Science/PythonTsunami
# conda env update --file PythonTsunami/environment.yml